// ─── Project Data (Single Source of Truth) ───

export const PROJECTS = [
    {
        href: '/physsim',
        title: 'Relativistic N-Body',
        shortDesc: 'Gravitational, electromagnetic, and magnetic interactions at relativistic speeds.',
        longDesc: 'Interactive physics simulation with Barnes-Hut algorithm, relativistic momentum, and real-time force visualization. Gravitational, electromagnetic, and magnetic interactions at O(N log N).',
        tags: ['physics', 'canvas', 'barnes-hut'],
        image: 'img/physsim.png',
        icon: '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 2a10 10 0 0 1 0 20M12 2a10 10 0 0 0 0 20M2 12h20"/></svg>',
        external: false,
    },
    {
        href: '/biosim',
        title: 'Cellular Metabolism',
        shortDesc: 'Enzyme kinetics, substrate diffusion, and energy production in a living cell.',
        longDesc: 'Simulate metabolic pathways in a living cell. Enzyme kinetics, substrate diffusion, and energy production visualized as an interactive cellular dashboard.',
        tags: ['biology', 'simulation', 'metabolism'],
        image: 'img/biosim.png',
        icon: '<svg viewBox="0 0 24 24"><path d="M12 22c-4.97 0-9-2.69-9-6v-4c0-3.31 4.03-6 9-6s9 2.69 9 6v4c0 3.31-4.03 6-9 6z"/><path d="M3 12c0 3.31 4.03 6 9 6s9-2.69 9-6"/><ellipse cx="12" cy="6" rx="9" ry="6"/></svg>',
        external: false,
    },
    {
        href: '/gerry',
        title: 'Redistricting Simulator',
        shortDesc: 'Paint congressional districts and see how boundaries shape electoral outcomes.',
        longDesc: 'Paint congressional districts on a hex-tile map and see how boundaries shape electoral outcomes. Real-time efficiency gap, compactness, and contiguity analysis.',
        tags: ['politics', 'svg', 'gerrymandering'],
        image: 'img/gerry.png',
        icon: '<svg viewBox="0 0 24 24"><path d="M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z"/></svg>',
        external: false,
    },
    {
        href: 'https://github.com/a9lim/shannon',
        title: 'Shannon',
        shortDesc: 'Autonomous AI assistant for Discord and Signal with web browsing, command execution, and task scheduling.',
        longDesc: 'Autonomous AI assistant that communicates over Discord and Signal. Browses the web, executes system commands, schedules tasks, and delegates programming work.',
        tags: ['python', 'llm', 'automation'],
        image: 'img/shannon.png',
        icon: '<svg viewBox="0 0 24 24"><path d="M12 2a2 2 0 0 1 2 2c0 .74-.4 1.39-1 1.73V7h1a7 7 0 0 1 7 7h1a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-1.07A7 7 0 0 1 14 22h-4a7 7 0 0 1-6.93-6H2a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1h1a7 7 0 0 1 7-7h1V5.73c-.6-.34-1-.99-1-1.73a2 2 0 0 1 2-2z"/><circle cx="9" cy="15" r="1"/><circle cx="15" cy="15" r="1"/></svg>',
        external: true,
    },
    {
        href: 'https://github.com/a9lim/Raiko',
        title: 'Raiko',
        shortDesc: 'Discord music and chat bot with queue management and conversational AI.',
        longDesc: 'Discord music and chat bot. Plays audio from YouTube, SoundCloud, and other sources with queue management, playlists, and conversational AI features.',
        tags: ['discord', 'java', 'music'],
        image: 'img/raiko.png',
        icon: '<svg viewBox="0 0 24 24"><path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/></svg>',
        external: true,
    },
    {
        href: 'https://github.com/a9lim/faithful',
        title: 'Faithful',
        shortDesc: 'Discord chatbot that emulates given messages in the style of source material.',
        longDesc: 'Discord chatbot that emulates given messages. Feed it a corpus of text and it generates responses in the style of the source material.',
        tags: ['discord', 'chatbot', 'nlp'],
        image: 'img/faithful.png',
        icon: '<svg viewBox="0 0 24 24"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>',
        external: true,
    },
    {
        href: 'https://github.com/catppuccin/sddm',
        title: 'Catppuccin for SDDM',
        shortDesc: 'Soothing pastel theme for the SDDM display manager with all four flavor variants.',
        longDesc: 'Soothing pastel theme for the SDDM display manager. Brings the Catppuccin color palette to the Linux login screen with all four flavor variants.',
        tags: ['linux', 'theme', 'catppuccin'],
        image: 'img/catppuccin.webp',
        icon: '<svg viewBox="0 0 24 24"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>',
        external: true,
    },
];
