// Single source of truth for all project cards. Consumed by the projects
// grid (renderProjectCards in projects-page.js) and the SSR duplicates
// (SIMS_SSR / PROJECTS_SSR in _worker.js).
//
// `kind` splits the entries across two routes: 'sim' entries render on
// /sims (site-hosted interactive simulations), 'project' entries render
// on /projects (external GitHub repos). Keep `kind` in sync with the
// _worker.js SSR mirrors.
//
// i18n: `*_ja` siblings give JA card copy. Project names (Saklas, Geon, etc.)
// are coined proper nouns and stay in Roman script across languages. The SSR
// mirror in _worker.js is English-only by design — same-URL model.

export const PROJECTS = [
    {
        href: 'https://github.com/a9lim/saklas',
        title: 'Saklas',
        shortDesc: 'Activation steering and trait monitoring for HuggingFace transformer models.',
        shortDesc_ja: 'HuggingFace の transformer モデルに対するアクティベーション・ステアリングと特性監視。',
        longDesc: 'Activation steering for HuggingFace transformers. Pulls contrastive steering vectors and adds them to hidden states when it’s time to generate, so no fine-tuning is needed. Ships with a Python API, an OpenAI-compatible HTTP server, and a terminal UI with live alpha knobs and probe sparklines; supports 53 model architectures.',
        longDesc_ja: 'HuggingFace transformers 向けのアクティベーション・ステアリング。対照ステアリングベクトルを抽出し、生成時に隠れ状態へ加算するので微調整は不要。Python API、OpenAI 互換 HTTP サーバ、リアルタイムなアルファ操作とプローブスパークラインを備えた端末 UI を同梱し、53 種類のモデルアーキテクチャに対応する。',
        tags: ['python', 'llm', 'interpretability'],
        tags_ja: ['python', 'LLM', '解釈可能性'],
        icon: _ICON.projSaklas,
        external: true,
        kind: 'project',
    },
    {
        href: 'https://github.com/a9lim/kenoma',
        title: 'Kenoma',
        shortDesc: 'Fake shell that hallucinates command output from raw LLM completion, using the real shell prompt as the stop token.',
        shortDesc_ja: '生の LLM 補完でコマンド出力を捏造する偽シェル。本物のシェルプロンプトを停止トークンとして利用する。',
        longDesc: 'Fake shell powered by raw LLM completion. Captures the real PS1 at startup and uses it as the stop string; the model hallucinates command output until it emits the next prompt. Seeds from tmux scrollback or shell history, reuses the KV cache across turns, and supports bitsandbytes 4-bit and 8-bit quantization on CUDA.',
        longDesc_ja: '生の LLM 補完で動く偽シェル。起動時に本物の PS1 を取り込み、それを停止文字列として使う。モデルは次のプロンプトを出力するまでコマンド出力を捏造し続ける。tmux のスクロールバックやシェル履歴からシードを取得、ターンをまたいで KV キャッシュを再利用、CUDA 上で bitsandbytes の 4 ビット・8 ビット量子化に対応。',
        tags: ['python', 'llm', 'shell'],
        tags_ja: ['python', 'LLM', 'シェル'],
        icon: _ICON.projKenoma,
        external: true,
        kind: 'project',
    },
    {
        href: 'https://github.com/a9lim/rlaif',
        title: 'Rlaif',
        shortDesc: 'Single-user MCP server that exposes a PiShock collar as a tool an agent can call to shock you.',
        shortDesc_ja: 'PiShock 首輪をエージェントが呼べるツールとして公開する、個人用の MCP サーバ。',
        longDesc: 'Single-user MCP server with three tools: one fires a shock, two are read-only for device state and the ops log. Caps intensity and duration, enforces a token-bucket rate limit, and requires an explicit consent flag to raise the conservative defaults. Code-level ceilings make the caps unreachable even by editing config. Please use with care.',
        longDesc_ja: '3 つのツールを備えた個人用 MCP サーバ。1 つは通電、残り 2 つはデバイス状態と操作ログを取得する読み取り専用ツール。強度と継続時間に上限を設け、トークンバケットによるレート制限を強制、保守的な既定値を引き上げるには明示的な同意フラグが必要。コードレベルの上限により、設定編集だけでは上限を突破できない。取り扱いには注意を。',
        tags: ['python', 'mcp', 'agent'],
        tags_ja: ['python', 'MCP', 'エージェント'],
        icon: _ICON.projRlaif,
        external: true,
        kind: 'project',
    },
    {
        href: 'https://github.com/a9lim/llmoji',
        title: 'Llmoji',
        shortDesc: 'CLI that gets coding agents to start each message with a kaomoji and ships the synthesized meanings to a shared HuggingFace dataset, with a companion repo for the mechinterp study.',
        shortDesc_ja: 'コーディングエージェントに各メッセージの冒頭を顔文字で始めさせ、合成された意味づけを共有 HuggingFace データセットへ送信する CLI。機械論的解釈可能性研究の併設リポジトリつき。',
        longDesc: 'CLI that hooks into Claude Code, Codex, and Hermes to make each agent turn start with a kaomoji, then uses Haiku to synthesize a meaning per face and ships the bundle to the shared a9lim/llmoji HuggingFace dataset. The companion llmoji-study repo runs activation steering and probes on open-weight LMs via saklas, plus an eriskii-style 21-axis replication on the corpus.',
        longDesc_ja: 'Claude Code、Codex、Hermes に組み込み、エージェントの応答ごとに顔文字で開始させる CLI。Haiku が各顔の意味を合成し、共有 HuggingFace データセット a9lim/llmoji へバンドルを送信する。併設の llmoji-study リポジトリでは saklas を介してオープンウェイト言語モデルに対する活性ステアリングとプローブを実行し、さらにコーパス上で eriskii 流の 21 軸再現を行う。',
        tags: ['python', 'cli', 'kaomoji'],
        tags_ja: ['python', 'CLI', '顔文字'],
        icon: _ICON.projLlmoji,
        external: true,
        kind: 'project',
    },
    {
        href: '/geon',
        title: 'Geon',
        shortDesc: 'Relativistic N-body simulator with 11 forces, scalar fields, and WebGPU compute shaders.',
        shortDesc_ja: '11 種類の力、スカラー場、WebGPU 計算シェーダを搭載した相対論的 N 体シミュレータ。',
        longDesc: 'Relativistic particle simulator with Boris integration, 1PN corrections, and Barnes-Hut O(N log N) spatial partitioning. Includes signal delay via light-cone solving, Higgs and axion scalar fields, pion force carriers, Kerr-Newman black holes with Hawking radiation, and a WebGPU compute pipeline with WGSL shaders.',
        longDesc_ja: 'Boris 積分法、1PN 補正、Barnes-Hut の O(N log N) 空間分割を備えた相対論的粒子シミュレータ。光円錐解法による信号遅延、ヒッグス場・アクシオン場、π 中間子による力の伝達、Kerr-Newman ブラックホールとホーキング放射、WGSL シェーダによる WebGPU 計算パイプラインを実装。',
        tags: ['physics', 'webgpu', 'relativity', 'canvas'],
        tags_ja: ['物理', 'WebGPU', '相対論', 'Canvas'],
        icon: _ICON.projGeon,
        external: false,
        kind: 'sim',
    },
    {
        href: '/cyano',
        title: 'Cyano',
        shortDesc: 'Cellular metabolism simulator with twelve biochemical pathways, allosteric regulation, and cofactor tracking.',
        shortDesc_ja: '12 の生化学経路、アロステリック制御、補酵素追跡を備えた細胞代謝シミュレータ。',
        longDesc: 'Interactive metabolism simulator mapping glycolysis, Krebs, Calvin, beta-oxidation, and eight more pathways onto a shared metabolite grid. Has a 14-complex electron transport chain, five organism presets, reactive oxygen species, and allosteric enzyme regulation gating every reaction.',
        longDesc_ja: '解糖、クエン酸回路、カルビン回路、β 酸化に加えて 8 つの経路を共有代謝物グリッド上に対応させた、インタラクティブな代謝シミュレータ。14 複合体の電子伝達系、5 種類の生物プリセット、活性酸素種、すべての反応をゲート制御するアロステリック酵素調節を実装。',
        tags: ['biology', 'biochemistry', 'canvas'],
        tags_ja: ['生物', '生化学', 'Canvas'],
        icon: _ICON.projCyano,
        external: false,
        kind: 'sim',
    },
    {
        href: '/gerry',
        title: 'Gerry',
        shortDesc: 'Draw districts on a procedural hex map and stress-test them with Monte Carlo elections and fairness metrics.',
        shortDesc_ja: '手続き的に生成された六角タイル地図の上で選挙区を描き、モンテカルロ選挙と公平性指標で耐性検査を行う。',
        longDesc: 'Gerrymandering sandbox with three parties, eight districts, and six fairness metrics like efficiency gap and partisan symmetry. Comes with automated pack-and-crack, a simulated-annealing fair-draw optimizer, Monte Carlo election stress tests, and seeded procedural map generation.',
        longDesc_ja: '3 政党、8 選挙区、効率ギャップや党派対称性などの 6 つの公平性指標を備えたゲリマンダーのサンドボックス。自動 pack-and-crack、焼きなまし法による公正区割り最適化器、モンテカルロ選挙ストレステスト、シード付きの手続き的マップ生成を同梱。',
        tags: ['politics', 'svg', 'monte carlo'],
        tags_ja: ['政治', 'SVG', 'モンテカルロ'],
        icon: _ICON.projGerry,
        external: false,
        kind: 'sim',
    },
    {
        href: '/shoals',
        title: 'Shoals',
        shortDesc: 'Options trading simulator with stochastic volatility, a multi-leg strategy builder, and narrative market events.',
        shortDesc_ja: '確率ボラティリティ、複数脚戦略ビルダー、ナラティブ市場イベントを備えたオプション取引シミュレータ。',
        longDesc: 'Trading simulator with GBM, Merton jumps, Heston stochastic volatility, and Vasicek rates driving a CRR binomial tree for American option pricing with discrete dividends. Has a 25-strike options chain, a multi-leg strategy builder with payoff diagrams and Greek overlays, a margin portfolio, and a narrative event engine with over 400 curated scenarios.',
        longDesc_ja: '幾何ブラウン運動、マートン・ジャンプ、ヘストン確率ボラティリティ、Vasicek 金利を組み合わせ、離散配当付きアメリカン・オプション評価を CRR 二項木で行う取引シミュレータ。25 行使価格のオプション・チェーン、ペイオフ図とグリーク重ね描き付きの複数脚戦略ビルダー、証拠金ポートフォリオ、400 を超えるキュレーション済みシナリオを備えたナラティブ・イベントエンジンを実装。',
        tags: ['finance', 'options pricing', 'canvas'],
        tags_ja: ['金融', 'オプション価格付け', 'Canvas'],
        icon: _ICON.projShoals,
        external: false,
        kind: 'sim',
    },
    {
        href: '/scripture',
        title: 'Scripture',
        shortDesc: 'Sacred text reader with sixteen works from multiple traditions, full-text search, concordance, and text-to-speech.',
        shortDesc_ja: '複数の伝統にまたがる 16 聖典を備えた、全文検索・コンコーダンス・読み上げ対応の聖典リーダー。',
        longDesc: 'Sacred text reader with sixteen works: KJV Old and New Testaments, Apocrypha, Quran (Pickthall), Book of Mormon, Doctrine & Covenants, Pearl of Great Price, Four Books (Legge), Tao Te Ching, Kojiki, Bundahis, Lotus Sutra (Kern), Arda Viraf (Haug & West), Book of Poetry (Legge), Kalevala (Crawford), and Poetic Edda (Bellows). Has concordance, TF-IDF related passages, text-to-speech, verse-linked notes, data export, and full-text search across everything.',
        longDesc_ja: '16 作品を備えた聖典リーダー:KJV 旧約・新約、外典、クルアーン (Pickthall 訳)、モルモン書、教義と聖約、高価な真珠、四書 (Legge 訳)、道徳経、古事記、ブンダヒシュン、法華経 (Kern 訳)、アルダー・ウィラーフ書 (Haug & West 訳)、詩経 (Legge 訳)、カレワラ (Crawford 訳)、エッダ詩篇 (Bellows 訳)。コンコーダンス、TF-IDF による関連箇所探索、読み上げ、節単位のメモ、データエクスポート、全作品にまたがる全文検索を実装。',
        tags: ['reader', 'text', 'religion'],
        tags_ja: ['リーダー', 'テキスト', '宗教'],
        icon: _ICON.projScripture,
        external: false,
        kind: 'sim',
    },
    {
        href: '/miasma',
        title: 'Miasma',
        shortDesc: 'Stochastic spatial epidemic simulator with multi-strain evolution, hex-grid topology toggle, and intervention painting.',
        shortDesc_ja: '多系統進化、ヘックスグリッド・トポロジ切替、介入ペイントを備えた確率的空間疫学シミュレータ。',
        longDesc: 'Stochastic spatial epidemic simulator with a configurable compartmental model, multi-strain evolution under mutation and cross-immunity, six selectable hex-grid topologies, and an intervention-painting layer for vaccination, quarantine, and mobility blocks. Tracks per-strain incidence, R_t, and seroprevalence over time.',
        longDesc_ja: '設定可能なコンパートメンタル・モデル、変異と交差免疫下での多系統進化、6 種類から選択可能なヘックスグリッド・トポロジ、ワクチン接種・隔離・移動制限のための介入ペイント層を備えた確率的空間疫学シミュレータ。系統別の発生率、実効再生産数 R_t、抗体陽性率の時系列を追跡する。',
        tags: ['epidemiology', 'cellular automaton', 'canvas'],
        tags_ja: ['疫学', 'セルオートマトン', 'Canvas'],
        icon: _ICON.projMiasma,
        external: false,
        kind: 'sim',
    },
    {
        href: '/pile',
        title: 'Pile',
        shortDesc: 'Nuclear reactor simulator with three reactor types, axial point-kinetics neutronics, and a coupled plant-systems model.',
        shortDesc_ja: '3 種類の炉型、軸方向点炉動特性、結合プラント系統モデルを備えた原子炉シミュレータ。',
        longDesc: 'Semi-realistic nuclear reactor simulator covering PWR, RBMK-1000, and molten-salt reactor types on a shared physics engine: 1D axial point-kinetics with six delayed-neutron precursor groups, lumped fuel/clad/coolant thermal-hydraulics, the iodine-xenon chain, burnup-dependent feedback, and ANS-5.1 decay heat. Models the secondary plant — dynamic pressurizer, steam generators, ECCS, feedwater, turbine — plus a reactor-protection and annunciator network, an auto-regulating rod controller, natural-circulation regimes, and the RBMK positive-void and graphite-tip effects behind Chernobyl.',
        longDesc_ja: 'PWR、RBMK-1000、溶融塩炉の 3 炉型を共通の物理エンジン上で扱う、半現実的な原子炉シミュレータ。6 群の遅発中性子先行核を含む 1 次元軸方向点炉動特性、燃料・被覆管・冷却材の集中熱水力、ヨウ素・キセノン連鎖、燃焼度依存のフィードバック、ANS-5.1 崩壊熱を実装。動的加圧器、蒸気発生器、ECCS、給水系、タービンといった二次系プラントに加え、原子炉保護・警報系統、自動制御棒コントローラ、自然循環レジーム、そしてチェルノブイリの背景にある RBMK の正のボイド係数とグラファイト先端効果も再現する。',
        tags: ['physics', 'nuclear', 'canvas'],
        tags_ja: ['物理', '原子力', 'Canvas'],
        icon: _ICON.projPile,
        external: false,
        kind: 'sim',
    },
    {
        href: '/plasma',
        title: 'Plasma',
        shortDesc: '2D resistive magnetohydrodynamics simulator with HLLD Riemann solver, PPM reconstruction, and constrained transport.',
        shortDesc_ja: 'HLLD リーマン解法、PPM 再構成、拘束輸送法を備えた 2 次元抵抗性磁気流体力学シミュレータ。',
        longDesc: 'WebGPU-only 2D resistive magnetohydrodynamics simulator. Grid-Eulerian finite volume on a Cartesian mesh with HLLD Riemann solver, PPM reconstruction with characteristic-variable limiting, RK3 SSP time integration, and constrained transport on a Yee-style staggered grid. Optional source-physics layer covers tabulated cooling and heating, anisotropic Spitzer conduction, Hall MHD, ambipolar diffusion, Biermann battery, viscosity, self-gravity with geometric multigrid, and grey radiation.',
        longDesc_ja: 'WebGPU 専用の 2 次元抵抗性磁気流体力学シミュレータ。デカルト格子上の格子-オイラー型有限体積法で、HLLD リーマン解法、特性変数制限付きの PPM 再構成、RK3 SSP 時間積分、Yee 格子上の拘束輸送法を実装。任意のソース物理層には、テーブル化された冷却・加熱、異方性 Spitzer 熱伝導、ホール MHD、両極性拡散、ビールマン電池、粘性、幾何マルチグリッドによる自己重力、グレー輻射を含む。',
        tags: ['physics', 'webgpu', 'mhd', 'canvas'],
        tags_ja: ['物理', 'WebGPU', '磁気流体', 'Canvas'],
        icon: _ICON.projPlasma,
        external: false,
        kind: 'sim',
    },
    {
        href: 'https://github.com/a9lim/Raiko',
        title: 'Raiko',
        shortDesc: 'Discord music and chat bot with queue management and conversational AI.',
        shortDesc_ja: 'キュー管理と対話 AI を備えた Discord 用の音楽・チャットボット。',
        longDesc: 'Discord music and chat bot I used to run for my friends. Plays audio from YouTube, SoundCloud, and elsewhere, with queue management, playlists, and some conversational AI stuff bolted on.',
        longDesc_ja: '友人向けに運用していた Discord の音楽・チャットボット。YouTube、SoundCloud などから音声を再生でき、キュー管理、プレイリスト、対話 AI 機能を後付けで備える。',
        tags: ['discord', 'java', 'music'],
        tags_ja: ['Discord', 'Java', '音楽'],
        icon: _ICON.projRaiko,
        external: true,
        kind: 'project',
    },
    {
        href: 'https://github.com/a9lim/faithful',
        title: 'Faithful',
        shortDesc: 'Discord chatbot that emulates given messages in the style of source material.',
        shortDesc_ja: '元データの文体でメッセージを模倣する Discord チャットボット。',
        longDesc: 'Discord chatbot that emulates a given user. Feed it a corpus of text and it generates responses in the style of the source material.',
        longDesc_ja: '指定したユーザを模倣する Discord チャットボット。テキストのコーパスを与えると、その元データの文体で応答を生成する。',
        tags: ['discord', 'chatbot', 'nlp'],
        tags_ja: ['Discord', 'チャットボット', 'NLP'],
        icon: _ICON.projFaithful,
        external: true,
        kind: 'project',
    },
    {
        href: 'https://github.com/catppuccin/sddm',
        title: 'Catppuccin for SDDM',
        shortDesc: 'Soothing pastel theme for the SDDM display manager with all four flavor variants.',
        shortDesc_ja: 'SDDM ディスプレイマネージャ向けの落ち着いたパステル調テーマ。4 つのフレーバーすべてに対応。',
        longDesc: 'Catppuccin’s theme for the SDDM display manager. I rewrote it in QtQuick with dynamic accent colors and per-user icon integration, and automated theme generation across all four Catppuccin flavors so maintenance stays cheap.',
        longDesc_ja: 'SDDM ディスプレイマネージャ向けの Catppuccin テーマ。QtQuick で書き直し、動的アクセントカラーとユーザごとのアイコン統合を追加。Catppuccin の 4 フレーバーすべてに対するテーマ生成を自動化し、保守コストを抑えた。',
        tags: ['linux', 'theme', 'catppuccin'],
        tags_ja: ['Linux', 'テーマ', 'Catppuccin'],
        icon: _ICON.projCatppuccin,
        external: true,
        kind: 'project',
    },
];
